import { DepartmentState, GroupState, PatternState, PermissionState, RoleState, ExtraInformationState } from './basic-states';
import { AuthenticationState, LanguageState, LoadingState, SettingState } from './extra-states';
import { CommentState, ConditionState, WorkFlowConnectionState, WorkFlowInstanceState, WorkFlowState, WorkFlowStepInstanceState, WorkFlowStepState } from './bpmn-states';
import {  CustomerExtraInformationDataState, CustomerState } from './customer-states';
import {  ProductExtraInformationDataState, ProductState } from './product-states';
import {  AccountExtraInformationDataState, AccountState } from './account-states';
import { FormControlState, FormDataState, FormGroupState, FormValueState } from './form-states';
export * from './basic-states';
export * from './extra-states';
export * from './bpmn-states';
export * from './customer-states';
export * from './account-states';
export * from './form-states';
export * from './product-states';

export class RootState {
  department: DepartmentState;
  group: GroupState;
  pattern: PatternState;
  permission: PermissionState;
  role: RoleState;
  loading: LoadingState;
  language: LanguageState;
  comment: CommentState;
  condition: ConditionState;
  workFlowConnection: WorkFlowConnectionState;
  workFlowInstance: WorkFlowInstanceState;
  workFlow: WorkFlowState;
  workFlowStepInstance: WorkFlowStepInstanceState;
  workFlowStep: WorkFlowStepState;
  customerExtraInformationData: CustomerExtraInformationDataState;
  customer: CustomerState;
  productExtraInformationData: ProductExtraInformationDataState;
  product: ProductState;
  accountExtraInformationData: AccountExtraInformationDataState;
  extraInformation: ExtraInformationState;
  account: AccountState;
  formControl: FormControlState;
  formData: FormDataState;
  formValue: FormValueState;
  formGroup: FormGroupState;
  authentication: AuthenticationState;
  setting: SettingState;
  constructor(props: RootState) {
    this.department = props.department;
    this.group = props.group;
    this.pattern = props.pattern;
    this.permission = props.permission;
    this.role = props.role;
    this.loading = props.loading;
    this.language = props.language;
    this.comment = props.comment;
    this.condition = props.condition;
    this.workFlowConnection = props.workFlowConnection;
    this.workFlowInstance = props.workFlowInstance;
    this.workFlow = props.workFlow;
    this.workFlowStepInstance = props.workFlowStepInstance;
    this.workFlowStep = props.workFlowStep;
    this.customerExtraInformationData = props.customerExtraInformationData;
    this.customer = props.customer;
    this.productExtraInformationData = props.productExtraInformationData;
    this.product = props.product;
    this.accountExtraInformationData = props.accountExtraInformationData;
    this.extraInformation = props.extraInformation;
    this.account = props.account;
    this.formControl = props.formControl;
    this.formData = props.formData;
    this.formValue = props.formValue;
    this.formGroup = props.formGroup;
    this.authentication = props.authentication;
    this.setting = props.setting;
  }
}