export const COMMENT_TYPE = {
  GETALL: {
      FETCH: 'COMMENT/GETALL',
      SUCCESS: 'COMMENT/GETALL/SUCCESS',
      ERROR: 'COMMENT/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'COMMENT/CREATE',
      SUCCESS: 'COMMENT/CREATE/SUCCESS',
      ERROR: 'COMMENT/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'COMMENT/UPDATE',
      SUCCESS: 'COMMENT/UPDATE/SUCCESS',
      ERROR: 'COMMENT/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'COMMENT/REMOVE',
      SUCCESS: 'COMMENT/REMOVE/SUCCESS',
      ERROR: 'COMMENT/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'COMMENT/RESET',
  },
};