export const CONDITION_TYPE = {
  GETALL: {
      FETCH: 'CONDITION/GETALL',
      SUCCESS: 'CONDITION/GETALL/SUCCESS',
      ERROR: 'CONDITION/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'CONDITION/CREATE',
      SUCCESS: 'CONDITION/CREATE/SUCCESS',
      ERROR: 'CONDITION/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'CONDITION/UPDATE',
      SUCCESS: 'CONDITION/UPDATE/SUCCESS',
      ERROR: 'CONDITION/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'CONDITION/REMOVE',
      SUCCESS: 'CONDITION/REMOVE/SUCCESS',
      ERROR: 'CONDITION/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'CONDITION/RESET',
  },
};