export const WORK_FLOW_STEP_INSTANCE_TYPE = {
  GETALL: {
      FETCH: 'WORK_FLOW_STEP_INSTANCE/GETALL',
      SUCCESS: 'WORK_FLOW_STEP_INSTANCE/GETALL/SUCCESS',
      ERROR: 'WORK_FLOW_STEP_INSTANCE/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'WORK_FLOW_STEP_INSTANCE/CREATE',
      SUCCESS: 'WORK_FLOW_STEP_INSTANCE/CREATE/SUCCESS',
      ERROR: 'WORK_FLOW_STEP_INSTANCE/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'WORK_FLOW_STEP_INSTANCE/UPDATE',
      SUCCESS: 'WORK_FLOW_STEP_INSTANCE/UPDATE/SUCCESS',
      ERROR: 'WORK_FLOW_STEP_INSTANCE/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'WORK_FLOW_STEP_INSTANCE/REMOVE',
      SUCCESS: 'WORK_FLOW_STEP_INSTANCE/REMOVE/SUCCESS',
      ERROR: 'WORK_FLOW_STEP_INSTANCE/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'WORK_FLOW_STEP_INSTANCE/RESET',
  },
};