export const WORK_FLOW_CONNECTION_TYPE = {
  GETALL: {
      FETCH: 'WORK_FLOW_CONNECTION/GETALL',
      SUCCESS: 'WORK_FLOW_CONNECTION/GETALL/SUCCESS',
      ERROR: 'WORK_FLOW_CONNECTION/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'WORK_FLOW_CONNECTION/CREATE',
      SUCCESS: 'WORK_FLOW_CONNECTION/CREATE/SUCCESS',
      ERROR: 'WORK_FLOW_CONNECTION/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'WORK_FLOW_CONNECTION/UPDATE',
      SUCCESS: 'WORK_FLOW_CONNECTION/UPDATE/SUCCESS',
      ERROR: 'WORK_FLOW_CONNECTION/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'WORK_FLOW_CONNECTION/REMOVE',
      SUCCESS: 'WORK_FLOW_CONNECTION/REMOVE/SUCCESS',
      ERROR: 'WORK_FLOW_CONNECTION/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'WORK_FLOW_CONNECTION/RESET',
  },
};