export const WORK_FLOW_STEP_TYPE = {
  GETALL: {
      FETCH: 'WORK_FLOW_STEP/GETALL',
      SUCCESS: 'WORK_FLOW_STEP/GETALL/SUCCESS',
      ERROR: 'WORK_FLOW_STEP/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'WORK_FLOW_STEP/CREATE',
      SUCCESS: 'WORK_FLOW_STEP/CREATE/SUCCESS',
      ERROR: 'WORK_FLOW_STEP/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'WORK_FLOW_STEP/UPDATE',
      SUCCESS: 'WORK_FLOW_STEP/UPDATE/SUCCESS',
      ERROR: 'WORK_FLOW_STEP/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'WORK_FLOW_STEP/REMOVE',
      SUCCESS: 'WORK_FLOW_STEP/REMOVE/SUCCESS',
      ERROR: 'WORK_FLOW_STEP/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'WORK_FLOW_STEP/RESET',
  },
};