export const WORK_FLOW_TYPE = {
  GETALL: {
      FETCH: 'WORK_FLOW/GETALL',
      SUCCESS: 'WORK_FLOW/GETALL/SUCCESS',
      ERROR: 'WORK_FLOW/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'WORK_FLOW/CREATE',
      SUCCESS: 'WORK_FLOW/CREATE/SUCCESS',
      ERROR: 'WORK_FLOW/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'WORK_FLOW/UPDATE',
      SUCCESS: 'WORK_FLOW/UPDATE/SUCCESS',
      ERROR: 'WORK_FLOW/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'WORK_FLOW/REMOVE',
      SUCCESS: 'WORK_FLOW/REMOVE/SUCCESS',
      ERROR: 'WORK_FLOW/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'WORK_FLOW/RESET',
  },
};