export const WORK_FLOW_TYPE = {
  GETALL: {
      FETCH: 'WORK_FLOW/GETALL',
      SUCCESS: 'WORK_FLOW/GETALL/SUCCESS',
      ERROR: 'WORK_FLOW/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'WORK_FLOW/CREATE',
      SUCCESS: 'WORK_FLOW/CREATE/SUCCESS',
      ERROR: 'WORK_FLOW/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'WORK_FLOW/UPDATE',
      SUCCESS: 'WORK_FLOW/UPDATE/SUCCESS',
      ERROR: 'WORK_FLOW/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'WORK_FLOW/REMOVE',
      SUCCESS: 'WORK_FLOW/REMOVE/SUCCESS',
      ERROR: 'WORK_FLOW/REMOVE/ERROR',
  },
  ACTIVE: {
    FETCH: 'WORK_FLOW/ACTIVE',
    SUCCESS: 'WORK_FLOW/ACTIVE/SUCCESS',
    ERROR: 'WORK_FLOW/ACTIVE/ERROR',
  },
  DEACTIVE: {
    FETCH: 'WORK_FLOW/DEACTIVE',
    SUCCESS: 'WORK_FLOW/DEACTIVE/SUCCESS',
    ERROR: 'WORK_FLOW/DEACTIVE/ERROR',
},
  RESET: {
      FETCH: 'WORK_FLOW/RESET',
  },
};