export const PRODUCT_TYPE = {
  GETALL: {
      FETCH: 'PRODUCT/GETALL',
      SUCCESS: 'PRODUCT/GETALL/SUCCESS',
      ERROR: 'PRODUCT/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'PRODUCT/CREATE',
      SUCCESS: 'PRODUCT/CREATE/SUCCESS',
      ERROR: 'PRODUCT/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'PRODUCT/UPDATE',
      SUCCESS: 'PRODUCT/UPDATE/SUCCESS',
      ERROR: 'PRODUCT/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'PRODUCT/REMOVE',
      SUCCESS: 'PRODUCT/REMOVE/SUCCESS',
      ERROR: 'PRODUCT/REMOVE/ERROR',
  },
  ACTIVE: {
    FETCH: 'PRODUCT/ACTIVE',
    SUCCESS: 'PRODUCT/ACTIVE/SUCCESS',
    ERROR: 'PRODUCT/ACTIVE/ERROR',
  },
  DEACTIVE: {
    FETCH: 'PRODUCT/DEACTIVE',
    SUCCESS: 'PRODUCT/DEACTIVE/SUCCESS',
    ERROR: 'PRODUCT/DEACTIVE/ERROR',
},
  RESET: {
      FETCH: 'PRODUCT/RESET',
  },
};