export const PRODUCT_EXTRA_INFORMATION_DATA_TYPE = {
  GETALL: {
      FETCH: 'PRODUCT_EXTRA_INFORMATION_DATA/GETALL',
      SUCCESS: 'PRODUCT_EXTRA_INFORMATION_DATA/GETALL/SUCCESS',
      ERROR: 'PRODUCT_EXTRA_INFORMATION_DATA/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'PRODUCT_EXTRA_INFORMATION_DATA/CREATE',
      SUCCESS: 'PRODUCT_EXTRA_INFORMATION_DATA/CREATE/SUCCESS',
      ERROR: 'PRODUCT_EXTRA_INFORMATION_DATA/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'PRODUCT_EXTRA_INFORMATION_DATA/UPDATE',
      SUCCESS: 'PRODUCT_EXTRA_INFORMATION_DATA/UPDATE/SUCCESS',
      ERROR: 'PRODUCT_EXTRA_INFORMATION_DATA/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'PRODUCT_EXTRA_INFORMATION_DATA/REMOVE',
      SUCCESS: 'PRODUCT_EXTRA_INFORMATION_DATA/REMOVE/SUCCESS',
      ERROR: 'PRODUCT_EXTRA_INFORMATION_DATA/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'PRODUCT_EXTRA_INFORMATION_DATA/RESET',
  },
};