export const DEPARTMENT_TYPE = {
  GETALL: {
      FETCH: 'DEPARTMENT/GETALL',
      SUCCESS: 'DEPARTMENT/GETALL/SUCCESS',
      ERROR: 'DEPARTMENT/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'DEPARTMENT/CREATE',
      SUCCESS: 'DEPARTMENT/CREATE/SUCCESS',
      ERROR: 'DEPARTMENT/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'DEPARTMENT/UPDATE',
      SUCCESS: 'DEPARTMENT/UPDATE/SUCCESS',
      ERROR: 'DEPARTMENT/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'DEPARTMENT/REMOVE',
      SUCCESS: 'DEPARTMENT/REMOVE/SUCCESS',
      ERROR: 'DEPARTMENT/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'DEPARTMENT/RESET',
  },
};