export const EXTRA_INFORMATION_TYPE = {
  GETALL: {
      FETCH: 'EXTRA_INFORMATION/GETALL',
      SUCCESS: 'EXTRA_INFORMATION/GETALL/SUCCESS',
      ERROR: 'EXTRA_INFORMATION/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'EXTRA_INFORMATION/CREATE',
      SUCCESS: 'EXTRA_INFORMATION/CREATE/SUCCESS',
      ERROR: 'EXTRA_INFORMATION/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'EXTRA_INFORMATION/UPDATE',
      SUCCESS: 'EXTRA_INFORMATION/UPDATE/SUCCESS',
      ERROR: 'EXTRA_INFORMATION/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'EXTRA_INFORMATION/REMOVE',
      SUCCESS: 'EXTRA_INFORMATION/REMOVE/SUCCESS',
      ERROR: 'EXTRA_INFORMATION/REMOVE/ERROR',
  },
  ACTIVE: {
    FETCH: 'EXTRA_INFORMATION/ACTIVE',
    SUCCESS: 'EXTRA_INFORMATION/ACTIVE/SUCCESS',
    ERROR: 'EXTRA_INFORMATION/ACTIVE/ERROR',
  },
  DEACTIVE: {
    FETCH: 'EXTRA_INFORMATION/DEACTIVE',
    SUCCESS: 'EXTRA_INFORMATION/DEACTIVE/SUCCESS',
    ERROR: 'EXTRA_INFORMATION/DEACTIVE/ERROR',
  },
  RESET: {
      FETCH: 'EXTRA_INFORMATION/RESET',
  },
};