export const GROUP_TYPE = {
  GETALL: {
      FETCH: 'GROUP/GETALL',
      SUCCESS: 'GROUP/GETALL/SUCCESS',
      ERROR: 'GROUP/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'GROUP/CREATE',
      SUCCESS: 'GROUP/CREATE/SUCCESS',
      ERROR: 'GROUP/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'GROUP/UPDATE',
      SUCCESS: 'GROUP/UPDATE/SUCCESS',
      ERROR: 'GROUP/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'GROUP/REMOVE',
      SUCCESS: 'GROUP/REMOVE/SUCCESS',
      ERROR: 'GROUP/REMOVE/ERROR',
  },
  ACTIVE: {
    FETCH: 'GROUP/ACTIVE',
    SUCCESS: 'GROUP/ACTIVE/SUCCESS',
    ERROR: 'GROUP/ACTIVE/ERROR',
  },
  DEACTIVE: {
    FETCH: 'GROUP/DEACTIVE',
    SUCCESS: 'GROUP/DEACTIVE/SUCCESS',
    ERROR: 'GROUP/DEACTIVE/ERROR',
  },
  RESET: {
      FETCH: 'GROUP/RESET',
  },
};