export const PATTERN_TYPE = {
  GETALL: {
      FETCH: 'PATTERN/GETALL',
      SUCCESS: 'PATTERN/GETALL/SUCCESS',
      ERROR: 'PATTERN/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'PATTERN/CREATE',
      SUCCESS: 'PATTERN/CREATE/SUCCESS',
      ERROR: 'PATTERN/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'PATTERN/UPDATE',
      SUCCESS: 'PATTERN/UPDATE/SUCCESS',
      ERROR: 'PATTERN/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'PATTERN/REMOVE',
      SUCCESS: 'PATTERN/REMOVE/SUCCESS',
      ERROR: 'PATTERN/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'PATTERN/RESET',
  },
};