export const PERMISSION_TYPE = {
  GETALL: {
      FETCH: 'PERMISSION/GETALL',
      SUCCESS: 'PERMISSION/GETALL/SUCCESS',
      ERROR: 'PERMISSION/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'PERMISSION/CREATE',
      SUCCESS: 'PERMISSION/CREATE/SUCCESS',
      ERROR: 'PERMISSION/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'PERMISSION/UPDATE',
      SUCCESS: 'PERMISSION/UPDATE/SUCCESS',
      ERROR: 'PERMISSION/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'PERMISSION/REMOVE',
      SUCCESS: 'PERMISSION/REMOVE/SUCCESS',
      ERROR: 'PERMISSION/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'PERMISSION/RESET',
  },
};