export const ROLE_TYPE = {
  GETALL: {
      FETCH: 'ROLE/GETALL',
      SUCCESS: 'ROLE/GETALL/SUCCESS',
      ERROR: 'ROLE/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'ROLE/CREATE',
      SUCCESS: 'ROLE/CREATE/SUCCESS',
      ERROR: 'ROLE/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'ROLE/UPDATE',
      SUCCESS: 'ROLE/UPDATE/SUCCESS',
      ERROR: 'ROLE/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'ROLE/REMOVE',
      SUCCESS: 'ROLE/REMOVE/SUCCESS',
      ERROR: 'ROLE/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'ROLE/RESET',
  },
};