export const FORM_GROUP_TYPE = {
  GETALL: {
      FETCH: 'FORM_GROUP/GETALL',
      SUCCESS: 'FORM_GROUP/GETALL/SUCCESS',
      ERROR: 'FORM_GROUP/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'FORM_GROUP/CREATE',
      SUCCESS: 'FORM_GROUP/CREATE/SUCCESS',
      ERROR: 'FORM_GROUP/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'FORM_GROUP/UPDATE',
      SUCCESS: 'FORM_GROUP/UPDATE/SUCCESS',
      ERROR: 'FORM_GROUP/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'FORM_GROUP/REMOVE',
      SUCCESS: 'FORM_GROUP/REMOVE/SUCCESS',
      ERROR: 'FORM_GROUP/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'FORM_GROUP/RESET',
  },
};