export const FORM_VALUE_TYPE = {
  GETALL: {
      FETCH: 'FORM_VALUE/GETALL',
      SUCCESS: 'FORM_VALUE/GETALL/SUCCESS',
      ERROR: 'FORM_VALUE/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'FORM_VALUE/CREATE',
      SUCCESS: 'FORM_VALUE/CREATE/SUCCESS',
      ERROR: 'FORM_VALUE/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'FORM_VALUE/UPDATE',
      SUCCESS: 'FORM_VALUE/UPDATE/SUCCESS',
      ERROR: 'FORM_VALUE/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'FORM_VALUE/REMOVE',
      SUCCESS: 'FORM_VALUE/REMOVE/SUCCESS',
      ERROR: 'FORM_VALUE/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'FORM_VALUE/RESET',
  },
};