
export const FORM_CONTROL_TYPE = {
  GETALL: {
      FETCH: 'FORM_CONTROL/GETALL',
      SUCCESS: 'FORM_CONTROL/GETALL/SUCCESS',
      ERROR: 'FORM_CONTROL/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'FORM_CONTROL/CREATE',
      SUCCESS: 'FORM_CONTROL/CREATE/SUCCESS',
      ERROR: 'FORM_CONTROL/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'FORM_CONTROL/UPDATE',
      SUCCESS: 'FORM_CONTROL/UPDATE/SUCCESS',
      ERROR: 'FORM_CONTROL/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'FORM_CONTROL/REMOVE',
      SUCCESS: 'FORM_CONTROL/REMOVE/SUCCESS',
      ERROR: 'FORM_CONTROL/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'FORM_CONTROL/RESET',
  },
};