export const FORM_GROUP_TYPE = {
  GETALL: {
      FETCH: 'FORM_GROUP/GETALL',
      SUCCESS: 'FORM_GROUP/GETALL/SUCCESS',
      ERROR: 'FORM_GROUP/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'FORM_GROUP/CREATE',
      SUCCESS: 'FORM_GROUP/CREATE/SUCCESS',
      ERROR: 'FORM_GROUP/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'FORM_GROUP/UPDATE',
      SUCCESS: 'FORM_GROUP/UPDATE/SUCCESS',
      ERROR: 'FORM_GROUP/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'FORM_GROUP/REMOVE',
      SUCCESS: 'FORM_GROUP/REMOVE/SUCCESS',
      ERROR: 'FORM_GROUP/REMOVE/ERROR',
  },
  ACTIVE: {
    FETCH: 'FORM_GROUP/ACTIVE',
    SUCCESS: 'FORM_GROUP/ACTIVE/SUCCESS',
    ERROR: 'FORM_GROUP/ACTIVE/ERROR',
  },
  DEACTIVE: {
    FETCH: 'FORM_GROUP/DEACTIVE',
    SUCCESS: 'FORM_GROUP/DEACTIVE/SUCCESS',
    ERROR: 'FORM_GROUP/DEACTIVE/ERROR',
},
  RESET: {
      FETCH: 'FORM_GROUP/RESET',
  },
};