export const ACCOUNT_EXTRA_INFORMATION_TYPE = {
  GETALL: {
      FETCH: 'ACCOUNT_EXTRA_INFORMATION/GETALL',
      SUCCESS: 'ACCOUNT_EXTRA_INFORMATION/GETALL/SUCCESS',
      ERROR: 'ACCOUNT_EXTRA_INFORMATION/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'ACCOUNT_EXTRA_INFORMATION/CREATE',
      SUCCESS: 'ACCOUNT_EXTRA_INFORMATION/CREATE/SUCCESS',
      ERROR: 'ACCOUNT_EXTRA_INFORMATION/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'ACCOUNT_EXTRA_INFORMATION/UPDATE',
      SUCCESS: 'ACCOUNT_EXTRA_INFORMATION/UPDATE/SUCCESS',
      ERROR: 'ACCOUNT_EXTRA_INFORMATION/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'ACCOUNT_EXTRA_INFORMATION/REMOVE',
      SUCCESS: 'ACCOUNT_EXTRA_INFORMATION/REMOVE/SUCCESS',
      ERROR: 'ACCOUNT_EXTRA_INFORMATION/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'ACCOUNT_EXTRA_INFORMATION/RESET',
  },
};