export const ACCOUNT_TYPE = {
  GETALL: {
      FETCH: 'ACCOUNT/GETALL',
      SUCCESS: 'ACCOUNT/GETALL/SUCCESS',
      ERROR: 'ACCOUNT/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'ACCOUNT/CREATE',
      SUCCESS: 'ACCOUNT/CREATE/SUCCESS',
      ERROR: 'ACCOUNT/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'ACCOUNT/UPDATE',
      SUCCESS: 'ACCOUNT/UPDATE/SUCCESS',
      ERROR: 'ACCOUNT/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'ACCOUNT/REMOVE',
      SUCCESS: 'ACCOUNT/REMOVE/SUCCESS',
      ERROR: 'ACCOUNT/REMOVE/ERROR',
  },
  ACTIVE: {
    FETCH: 'ACCOUNT/ACTIVE',
    SUCCESS: 'ACCOUNT/ACTIVE/SUCCESS',
    ERROR: 'ACCOUNT/ACTIVE/ERROR',
  },
  DEACTIVE: {
    FETCH: 'ACCOUNT/DEACTIVE',
    SUCCESS: 'ACCOUNT/DEACTIVE/SUCCESS',
    ERROR: 'ACCOUNT/DEACTIVE/ERROR',
},
  RESET: {
      FETCH: 'ACCOUNT/RESET',
  },
};