export const CUSTOMER_EXTRA_DATA_TYPE = {
  GETALL: {
      FETCH: 'CUSTOMER_EXTRA_DATA/GETALL',
      SUCCESS: 'CUSTOMER_EXTRA_DATA/GETALL/SUCCESS',
      ERROR: 'CUSTOMER_EXTRA_DATA/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'CUSTOMER_EXTRA_DATA/CREATE',
      SUCCESS: 'CUSTOMER_EXTRA_DATA/CREATE/SUCCESS',
      ERROR: 'CUSTOMER_EXTRA_DATA/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'CUSTOMER_EXTRA_DATA/UPDATE',
      SUCCESS: 'CUSTOMER_EXTRA_DATA/UPDATE/SUCCESS',
      ERROR: 'CUSTOMER_EXTRA_DATA/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'CUSTOMER_EXTRA_DATA/REMOVE',
      SUCCESS: 'CUSTOMER_EXTRA_DATA/REMOVE/SUCCESS',
      ERROR: 'CUSTOMER_EXTRA_DATA/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'CUSTOMER_EXTRA_DATA/RESET',
  },
};