export const CUSTOMER_EXTRA_INFORMATION_TYPE = {
  GETALL: {
    FETCH: 'CUSTOMER_EXTRA_INFORMATION/GETALL',
    SUCCESS: 'CUSTOMER_EXTRA_INFORMATION/GETALL/SUCCESS',
    ERROR: 'CUSTOMER_EXTRA_INFORMATION/GETALL/ERROR',
  },
  CREATE: {
    FETCH: 'CUSTOMER_EXTRA_INFORMATION/CREATE',
    SUCCESS: 'CUSTOMER_EXTRA_INFORMATION/CREATE/SUCCESS',
    ERROR: 'CUSTOMER_EXTRA_INFORMATION/CREATE/ERROR',
  },
  UPDATE: {
    FETCH: 'CUSTOMER_EXTRA_INFORMATION/UPDATE',
    SUCCESS: 'CUSTOMER_EXTRA_INFORMATION/UPDATE/SUCCESS',
    ERROR: 'CUSTOMER_EXTRA_INFORMATION/UPDATE/ERROR',
  },
  REMOVE: {
    FETCH: 'CUSTOMER_EXTRA_INFORMATION/REMOVE',
    SUCCESS: 'CUSTOMER_EXTRA_INFORMATION/REMOVE/SUCCESS',
    ERROR: 'CUSTOMER_EXTRA_INFORMATION/REMOVE/ERROR',
  },
  ACTIVE: {
    FETCH: 'CUSTOMER_EXTRA_INFORMATION/ACTIVE',
    SUCCESS: 'CUSTOMER_EXTRA_INFORMATION/ACTIVE/SUCCESS',
    ERROR: 'CUSTOMER_EXTRA_INFORMATION/ACTIVE/ERROR',
  },
  DEACTIVE: {
    FETCH: 'CUSTOMER_EXTRA_INFORMATION/DEACTIVE',
    SUCCESS: 'CUSTOMER_EXTRA_INFORMATION/DEACTIVE/SUCCESS',
    ERROR: 'CUSTOMER_EXTRA_INFORMATION/DEACTIVE/ERROR',
  },
  RESET: {
    FETCH: 'CUSTOMER_EXTRA_INFORMATION/RESET',
  },
};