export const CUSTOMER_TYPE = {
  GETALL: {
      FETCH: 'CUSTOMER/GETALL',
      SUCCESS: 'CUSTOMER/GETALL/SUCCESS',
      ERROR: 'CUSTOMER/GETALL/ERROR',
  },
  CREATE: {
      FETCH: 'CUSTOMER/CREATE',
      SUCCESS: 'CUSTOMER/CREATE/SUCCESS',
      ERROR: 'CUSTOMER/CREATE/ERROR',
  },
  UPDATE: {
      FETCH: 'CUSTOMER/UPDATE',
      SUCCESS: 'CUSTOMER/UPDATE/SUCCESS',
      ERROR: 'CUSTOMER/UPDATE/ERROR',
  },
  REMOVE: {
      FETCH: 'CUSTOMER/REMOVE',
      SUCCESS: 'CUSTOMER/REMOVE/SUCCESS',
      ERROR: 'CUSTOMER/REMOVE/ERROR',
  },
  RESET: {
      FETCH: 'CUSTOMER/RESET',
  },
};