export const AUTHENTICATION_TYPE = {
    GETALL: {
        FETCH: 'AUTHENTICATION/GETALL',
        SUCCESS: 'AUTHENTICATION/GETALL/SUCCESS',
        ERROR: 'AUTHENTICATION/GETALL/ERROR',
    },
    CREATE: {
        FETCH: 'AUTHENTICATION/CREATE',
        SUCCESS: 'AUTHENTICATION/CREATE/SUCCESS',
        ERROR: 'AUTHENTICATION/CREATE/ERROR',
    },
    UPDATE: {
        FETCH: 'AUTHENTICATION/UPDATE',
        SUCCESS: 'AUTHENTICATION/UPDATE/SUCCESS',
        ERROR: 'AUTHENTICATION/UPDATE/ERROR',
    },
    REMOVE: {
        FETCH: 'AUTHENTICATION/REMOVE',
        SUCCESS: 'AUTHENTICATION/REMOVE/SUCCESS',
        ERROR: 'AUTHENTICATION/REMOVE/ERROR',
    },
    RESET: {
        FETCH: 'AUTHENTICATION/RESET',
    },
    AUTHENTICATION: {
        FETCH: 'AUTHENTICATION/AUTHENTICATION',
        SUCCESS: 'AUTHENTICATION/AUTHENTICATION/SUCCESS',
        ERROR: 'AUTHENTICATION/AUTHENTICATION/ERROR',
    },
    CHECKLOGIN: {
        FETCH: 'AUTHENTICATION/CHECKLOGIN',
        SUCCESS: 'AUTHENTICATION/CHECKLOGIN/SUCCESS',
        ERROR: 'AUTHENTICATION/CHECKLOGIN/ERROR',
    },
    LOGIN: {
        FETCH: 'AUTHENTICATION/LOGIN',
        SUCCESS: 'AUTHENTICATION/LOGIN/SUCCESS',
        ERROR: 'AUTHENTICATION/LOGIN/ERROR',
    },
    FETCHING: {
        FETCH: 'AUTHENTICATION/FETCH',
    },
  };